### ISSUE TITLE
Doesn't work with nested list items e. g.: my_field = MyDataclassSerialzer(many=True)

### ISSUE THREAD

**Issue by ADR-007** [oxan/djangorestframework-dataclasses#13]
Hi!

I found some bug and some fix :)

The current version doesn't work with serializers like that:
```
class MyDataclassSerialzer1(...):
   ...
class MyDataclassSerializer2(...):
   my_field = MyDataclassSerialzer1(many=True)
   ...
```
The fix is simple! Just change this line:
https://github.com/oxan/djangorestframework-dataclasses/blob/f0a5321c12088e65a20f8c318116538d5ed60970/rest_framework_dataclasses/serializers.py#L105

to:
```python
            if isinstance(field, DataclassSerializer) or \
                    isinstance(field, rest_framework.serializers.ListSerializer) and \
                    isinstance(field.child, DataclassSerializer):
```

Someday I will have a time to make PR with tests, but not today :(

**Comment by oxan** [comment]
I expected something like this to popup from that horrible code :( I've pushed a fix, will leave the issue open until I've added tests for this.

**Comment by ADR-007** [comment]
Thanks!
