### ISSUE TITLE
Converting serialized data back to dataclass

### ISSUE THREAD

**Issue by errietta** [oxan/djangorestframework-dataclasses#21]
Hi,
given the following:
```
@dataclass
class Person():
  name: str


class PersonSerializer(DataclassSerializer):
  class Meta:
     dataclass = Person
````

When I have my json data from the client, I can serialize it with `serialized_data = PersonSerializer(data={'name':'alice'})`. However, if I call `is_valid()` and then `validated_data`, this will give me an `OrderedDict`, instead of a `Person` object. Am I missing something obvious, or do I just have to call `Person(**serialized_data)` to get it back to my `Person` dataclass?

**Comment by oxan** [comment]
Which version are you using? From 0.6 onwards `validated_data` should be an instance of the dataclass.

**Comment by errietta** [comment]
Yep, thanks @oxan I was on 0.4! I will update next time I have a weird problem 😂
