### ISSUE TITLE
`DataclassSerializer`'s pydoc leaks into OpenAPI generator

### ISSUE THREAD

**Issue by wkrueger** [oxan/djangorestframework-dataclasses#28]
The OpenAPI generator used here is drf-spectacular.

![image](https://user-images.githubusercontent.com/2209181/98190657-41396280-1ef6-11eb-88cd-e5cb34188b25.png)

**Comment by oxan** [comment]
I consider this a problem with drf-spectacular. It automatically ignores documentation from DRF itself, but doesn't do that for external libraries. Thus the only thing I can do here to fix this is to drop the docstring, and that's not an improvement. Luckily it seems that you can [customize](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/settings.py#L64) the behaviour of drf-spectacular.
