### ISSUE TITLE
How about performance ?

### ISSUE THREAD

**Issue by Kub-AT** [oxan/djangorestframework-dataclasses#37]
Hi,

How about performance ? 
Did you test large objects serialization performance ?

djangorestframework-dataclasses vs build-in drf serializer ?

**Comment by oxan** [comment]
I haven't done any benchmarks, but I'd expect it to be slower. The main reason is that the serializer has to rediscover and recreate the fields every time it is created. We could cache some information to improve this a bit, but it is mainly a limitation in the design of DRF's serializers. DRF's ModelSerializer also suffers from this problem (see encode/django-rest-framework#7093).
