### ISSUE TITLE
With drf-yasg, Dataclass name appears as "Dataclass" string instead of class name

### ISSUE THREAD

**Issue by akakakakakaa** [oxan/djangorestframework-dataclasses#41]
# Environment
```
python==3.8
Django==3.2.4
djangorestframework==3.12.4
djangorestframework-dataclasses==0.9
dataclasses-json==0.5.4
drf-yasg==1.20.0
```

# Problem

DataclassSerializer shows Dataclass name appears as "Dataclass" string instead of class name.

According to issue #14, it seems that even nested fields have proper names in the openapi format.

```python
#serializer for response
@dataclass
@dataclass_json
class JobInfo:
    name: str
    labels: Dict[str, str]
    status: str
    accelerator: str
    limits: float
    requests: float
    volumes: List[str]
    image: str
    command: str
    startTime: str
    completionTime: str


@dataclass
@dataclass_json
class JobInfos:
    jobNumber: int
    jobs: List[JobInfo]


class JobInfoGetResponseSerializer(DataclassSerializer):
    class Meta:
        dataclass = JobInfos
```

![image](https://user-images.githubusercontent.com/16163325/124501399-6f13d580-ddfc-11eb-93cc-af990e11d2ec.png)

**Comment by oxan** [comment]
Judging from a quick look at their code, I don't think this is something that can or should be fixed on our side. drf-yasg will need to be adapted for this.

**Comment by oxan** [comment]
You can probably workaround this by explicitly declaring the serializer, btw:

```python
class JobInfoSerializer(DataclassSerializer):
    class Meta:
        dataclass = JobInfo

class JobInfoGetResponseSerializer(DataclassSerializer):
    jobs = JobInfoSerializer(many=True)
    class Meta:
        dataclass = JobInfos
```

**Comment by oxan** [comment]
As I said before, this is not something that can be fixed from our side. Either somebody needs to contribute support to drf-yasg, or you need to declare the serializers for your nested classes explicitly.

**Comment by intgr** [comment]
My project moved from drf-yasg to drf-spectacular some time ago. With drf-spectacular, you can define an extension to get the dataclass name:

```
class OpenApiDataclassSerializerExtensions(OpenApiSerializerExtension):
    target_class = "rest_framework_dataclasses.serializers.DataclassSerializer"
    match_subclasses = True
    priority = 1

    def get_name(self) -> str:
        return self.target.dataclass_definition.dataclass_type.__name__
```

**Comment by dineshtrivedi** [comment]
@oxan I saw your response, however, I have accidentally posted an incomplete comment. I have updated it.

I just wanted to share what I have done so far just in case you want to change the project to a similar solution or in case @akakakakakaa wants to use the solution.

@intgr Thank you for your comment. I have been meaning to try drf-spectacular, I just haven't had time.
What was the reason why you changed from drf-yasg to drf-spectacular?

**Comment by dineshtrivedi** [comment]
Thank for your response @oxan

**Comment by intgr** [comment]
The immediate reason for switching to drf-spectacular was because we needed some OpenAPI 3 features. drf-yasg only supports OpenAPI 2. I don't think there were any downsides to migrating.

**Comment by dineshtrivedi** [comment]
Thank you @intgr
