### ISSUE TITLE
`.is_valid()` seems to return `False` even in minimal example

### ISSUE THREAD

**Issue by islerfab** [oxan/djangorestframework-dataclasses#43]
First of all, thanks for your work on this package. I've been using it successfully, but I've noticed and always ignored the fact that the `.is_valid()` call on the serializer returned `False`. I'd like to fix this to be able to take validation seriously, so I tried to find the issue. I may be doing something wrong, in this case, thanks for pointing me towards my mistake and forgiving me for having created this issue.

A minimal example based on your README (e.g., one can copy-paste this into the `manage.py shell`):
```python
import datetime
import typing

from dataclasses import dataclass
from rest_framework_dataclasses.serializers import DataclassSerializer

@dataclass
class Person:
  name: str
  email: str
  alive: bool
  gender: typing.Literal['male', 'female']
  birth_date: typing.Optional[datetime.date]
  phone: typing.List[str]
  movie_ratings: typing.Dict[str, int]

serializer = DataclassSerializer(
  dataclass=Person,
  data=Person(name="Foo",
    email="foo@bar.com",
    alive=True,
    gender="male",
    phone=["000"],
    birth_date=None,
    movie_ratings={}))
```

Then, in the same django shell:
```python
>>> serializer.is_valid()
False
>>> serializer._errors
{'non_field_errors': [ErrorDetail(string='Invalid data. Expected a dictionary, but got Person.', code='invalid')]}
```
This error is created when the DataclassSerializer is calling DRF's serializer's `to_internal_value(data)` method:
https://github.com/oxan/djangorestframework-dataclasses/blob/2d653d2daf00e876836e608bffc6ea8a3b4d9520/rest_framework_dataclasses/serializers.py#L596, where `data` is the `Person` object.

The validated data is still correct and can be sent out in a Response after having called `is_valid()`, but that's of course not how it's supposed to be used.

Thanks for having a quick look into this!

**Comment by oxan** [comment]
You're shouldn't pass a dataclass as the `data` parameter. It should contain the data to deserialize as a dictionary of primitives. It doesn't make sense for that to already be a dataclass, because what's there to deserialize then?

**Comment by islerfab** [comment]
I was quite sure I misunderstood something here. In my API, I'm collecting dataclass objects (e.g., `Person`s in this example), and then I'd like to send out serialized data. So my intention was not actually to deserialize (although I see now that this was what was going on when initializing the serializer), but only to serialize (it's a read-only API endpoint). I'm closing this issue, of course, but if you have in mind what I'm doing conceptionally wrong when my only plan is to serialize the dataclass object, feel free to still leave a comment. Thanks a lot!

**Comment by oxan** [comment]
If you want to serialize an object, pass the dataclass as the `instance` parameter (which is the first one). See DRF's [docs](https://www.django-rest-framework.org/api-guide/serializers/#serializing-objects) on serializers.
