### ISSUE TITLE
Serializing nested dataclasses using rest_framework.serilaizers.Field subclass

### ISSUE THREAD

**Issue by diachkov-lightit** [oxan/djangorestframework-dataclasses#46]
Hello, I'm really impressed with the work you've done with this library, but I have a small issue working with it.

I have the next dataclasses [declared](https://github.com/vitaliy-diachkov/drf-dataclasses-serialize-nested/blob/master/apps/users/dataclasses.py):

```python
from dataclasses import dataclass, field


@dataclass
class SocialSecurityNumber:
    number: str

    @property
    def hidden(self) -> str:
        return f'SSN <#{self.number}>'

    def __str__(self) -> str:
        return self.hidden


@dataclass
class Profile:
    email: str
    social_security_number: SocialSecurityNumber


@dataclass
class Group:
    name: str


@dataclass
class User:
    id: int
    username: str
    profile: Profile
    groups: list[Group]
```

Also, I have [implemented](https://github.com/vitaliy-diachkov/drf-dataclasses-serialize-nested/blob/master/apps/users/fields.py) my own serializer field to hide the social security number value (notice the constructor):

```python

from rest_framework.fields import Field


class SocialSecurityNumberField(Field):
    def __init__(self, *args, **kwargs):
        # kwargs.pop('dataclass', None)
        # kwargs.pop('many', None)
        super().__init__(*args, **kwargs)

    def to_representation(self, value):
        print('Called to_representation')
        return value.hidden
```

And I have my own [dataclass serializer](https://github.com/vitaliy-diachkov/drf-dataclasses-serialize-nested/blob/master/apps/users/serializers.py) (I am overriding it to set custom field for SocialSecurityNumber dataclass):

```python
class CustomDataclassSerializer(DataclassSerializer):
    serializer_field_mapping = {
        int:                  rest_framework.fields.IntegerField,
        float:                rest_framework.fields.FloatField,
        bool:                 rest_framework.fields.BooleanField,
        str:                  rest_framework.fields.CharField,
        decimal.Decimal:      fields.DefaultDecimalField,
        datetime.date:        rest_framework.fields.DateField,
        datetime.datetime:    rest_framework.fields.DateTimeField,
        datetime.time:        rest_framework.fields.TimeField,
        datetime.timedelta:   rest_framework.fields.DurationField,
        uuid.UUID:            rest_framework.fields.UUIDField,
        dict:                 rest_framework.fields.DictField,
        list:                 rest_framework.fields.ListField,
        SocialSecurityNumber: SocialSecurityNumberField
    }

    @property
    def serializer_dataclass_field(self):
        return CustomDataclassSerializer
```

The issue When this been invoked it tries for some reason to pass `dataclass` and `many` parameters to SocialSecurityNumberField (like it was a `rest_framework.serializers.Serializer` subclass), what I assume was not the expected behavior.

**Comment by vitaliy-diachkov** [comment]
Add another condition to check whether you have a `Field` mapped to the dataclass inside `serializer_field_mapping` and this `field` would pass the next condition: `isinstance(field, Field) and not isinstance(field, Serializer)`, idk
