### ISSUE TITLE
[Question]: Nested serializer with Union

### ISSUE THREAD

**Issue by felippemr** [oxan/djangorestframework-dataclasses#54]
👋  I have a dataclass that look like this:

```
@dc
class Document:
    id: UUID
    details: Union[ComplianceDoc, SignatureDoc]
    ...

@dc
class ComplianceDoc:
    ...

@dc
class SignatureDoc:
    ...
```

What is the expected behavior if I give this to a serializer? Currently it is just getting the first type within the `Union`.

**Comment by oxan** [comment]
From the [README](https://github.com/oxan/djangorestframework-dataclasses#field-mappings):

> Type unions are not supported yet.

Expected behavior is that you don't do that ;-)

I'm honestly not sure how type unions should work, though, particularly for deserialization. How should it know which type to expect?
