### ISSUE TITLE
Difference between inheritance and function

### ISSUE THREAD

**Issue by rvanlaar** [oxan/djangorestframework-dataclasses#56]
Hello,

djangorestframework-dataclasses is helping me document my API with drf-spectacular.
Thanks for that.

I noticed a inherited dataclass serializer is different than one created by a function.
An example:

```
@dataclass
class Monty:
    python: bool

MontySerializer = DataclassSerializer(dataclass=Monty)
class MontyClassSerializer(DataclassSerializer):
    class Meta:
        dataclass = Monty

monty = Monty(True)
MontyClassSerializer(instance = monty) # works
MontySerializer(instance=monty) # TypeError: 'DataclassSerializer' object is not callable
```

My expectation is that both, class and function would have the same result. 
It really doubles my code when it needs to be created as an actual class.
Is there a way around this?

**Comment by oxan** [comment]
There is no function: what you're doing is calling the constructor of the `DataclassSerializer` class, which returns a `DataclassSerializer` instance, not a type. It's meant to be used as substitution for the explicit type in places where you'd instantiate the serializer, not to create a serializer type. E.g. like this:
```python
ser = DataclassSerializer(dataclass=Monty, instance=monty)
# use in place of:
ser = MontyClassSerializer(instance=monty)
```

**Comment by rvanlaar** [comment]
Hi, Thank you for the reply. My expectations and what actually happens under the hood were mismatched. 
I do think there's value in using the syntax `DataclassSerializer(dataclass=Monty)` to return a class. 
Especially when the use case is documenting the REST API for `@api_view` functions.
