### ISSUE TITLE
"Invalid data. Expected a dictionary, but got <dataclass.type>"

### ISSUE THREAD

**Issue by mitchmahan** [oxan/djangorestframework-dataclasses#60]
When using a serializer class and passing it a list of dataclasses I get the following error:

"Invalid data. Expected a dictionary, but got <dataclass.type>"

Example:

@dataclass
Module:
  name: str

modules = [Module(name='foo'), Module(name='bar')]

class ModuleSerializer(DataclassSerializer):
    class Meta:
        dataclass = Module

ModuleSerializer(data=modules, many=True)

This requires me to first have to call:

modules_as_dicts = list(map(dataclasses.asdict, modules))

before passing the data to the serializer.

Seems odd for the serializer to not know how to access the dataclass data directly or use asdict internally?

**Comment by oxan** [comment]
The `data` parameter is for serialized data (i.e. lists and dicts) that should be deserialized, the `instance` parameter is for deserialized data (i.e. dataclass instances) that should be serialized.

**Comment by oxan** [comment]
Closing as not an actionable issue.
