### ISSUE TITLE
Mypy error: Type argument "X" of "DataclassSerializer" must be a subtype of "Dataclass"

### ISSUE THREAD

**Issue by intgr** [oxan/djangorestframework-dataclasses#64]
When using code like:

```python
@dataclass
class MyDataclass:
    blah: int


class MySerializer(DataclassSerializer[MyDataclass]):
    ...
```

mypy version 0.990 will display a warning like:

> Type argument "MyDataclass" of "DataclassSerializer" must be a subtype of "Dataclass"

I am not yet sure whether this is a bug or intentional change, reported to mypy for clarification: https://github.com/python/mypy/issues/14029

**Comment by oxan** [comment]
Marking `__dataclass_fields__` as a `ClassVar` in the protocol makes sense imo. It's unfortunate that older mypy doesn't accept that, though.

**Comment by intgr** [comment]
@oxan Are you fixing this or should I submit a PR?

**Comment by oxan** [comment]
I can commit a fix tomorrow.
